name: Build, Test & Publish Package

on:
  push:
    tags:
      - "v*.*.*"  

jobs:
  build-test-pack:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    defaults:
      run:
        working-directory: src

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      # 3️⃣ Restore
      - name: Restore dependencies
        run: dotnet restore

      # 4️⃣ Build
      - name: Build
        run: dotnet build --configuration Release --no-restore -warnaserror

      # 5️⃣ Test
      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal

      # 6️⃣ Pack
      - name: Pack NuGet package
        run: dotnet pack --configuration Release --no-build \
               /p:PackageVersion=${GITHUB_REF_NAME#v} \
               /p:ContinuousIntegrationBuild=true

      # 7️⃣ Publish to GitHub Packages
      - name: Publish package
        run: dotnet nuget push "bin/Release/*.nupkg" \
               --source "github" \
               --api-key ${{ secrets.GITHUB_TOKEN }}
