name: Build, Test & Pack

on:
  push:
    tags:
      - "v*.*.*"  

jobs:
  build-test-pack:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    defaults:
      run:
        working-directory: src

    steps:
      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --configuration Release --no-restore -warnaserror

      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal
    
      - name: Pack NuGet package
        run: dotnet pack ./NullaryThunk.Funky.Core/NullaryThunk.Funky.Core.csproj --no-build --configuration Release -p:PackageVersion=${GITHUB_REF_NAME#v}

      - name: NuGet push
        run: dotnet nuget push "./NullaryThunk.Funky.Core/bin/Release/*.nupkg" --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json